"""Generate the arXiv and TMLR variants from main.tex.

The three files used to be hand-maintained copies and had drifted apart (the
arXiv and TMLR versions still carried the v3 title and abstract after main.tex
was revised). They are now derived, so editing main.tex is the only step.

  arxiv/main.tex   identical body, using only standard TeX Live packages.
  tmlr/main.tex    identical body; swaps in the TMLR document class and title
                   block, and -- because TMLR review is double-blind --
                   removes the author block and the identifying repository
                   links, replacing them with anonymized placeholders.
                   Pass --deanonymize for the camera-ready version.

Usage:  python make_variants.py [--deanonymize]
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "main.tex")

TMLR_PREAMBLE = r"""% Generated by make_variants.py -- edit main.tex, not this file.
% SETUP: download tmlr.sty + tmlr.bst from the TMLR OpenReview template
%        (https://jmlr.org/tmlr/ -> Author Instructions) into this folder.
%        Compile with pdfLaTeX (bibliography is embedded, no .bib needed).
\documentclass{article}
\usepackage{tmlr}            % use \usepackage[accepted]{tmlr} for camera-ready
\usepackage{amsmath,amssymb}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{array}
\usepackage{microtype}
\usepackage{enumitem}
\setlist{itemsep=2pt,topsep=3pt}
\emergencystretch=2em
\newcommand{\jlens}{J\mbox{-}lens}
"""

TMLR_TITLE_ANON = r"""\title{\raggedright Persistent Agent Self-State Has Task- and Model-Dependent Effects on Value Adherence}
\author{\name Anonymous Author(s) \email anonymous@example.com \\
        \addr Anonymous Institution}
"""

TMLR_TITLE_NAMED = r"""\title{\raggedright Persistent Agent Self-State Has Task- and Model-Dependent Effects on Value Adherence}
\author{\name Wang Bihao \email oratiswang@gmail.com \\
        \addr Independent Researcher}
"""

# Strings that would identify the author to a double-blind reviewer.
ANON_SUBS = [
    (r"\\href\{https://github\.com/oratis/externalizing-the-workspace\}"
     r"\{github\.com/oratis/externalizing-the-workspace\}",
     "the anonymized supplementary archive"),
    (r"\\href\{https://huggingface\.co/HakkoLab\}\{huggingface\.co/HakkoLab\}",
     "an anonymized data archive"),
    (r"github\.com/oratis/externalizing-the-workspace",
     "anonymized-repository"),
    (r"Wang Bihao is the sole author", "The submission has a single author"),
    (r"Wang Bihao", "The author"),
]


def body_after_preamble(text):
    """Everything from \\begin{document} onwards."""
    i = text.index("\\begin{document}")
    return text[i:]


def main():
    deanon = "--deanonymize" in sys.argv
    src = open(SRC).read()

    # ---- arXiv: same file, with a generated-file banner ------------------
    arxiv = src.replace(
        "% Persistent Agent Self-State — preprint. Compile: tectonic main.tex",
        "% Generated by make_variants.py -- edit main.tex, not this file.")
    os.makedirs(os.path.join(HERE, "arxiv"), exist_ok=True)
    with open(os.path.join(HERE, "arxiv", "main.tex"), "w") as f:
        f.write(arxiv)

    # ---- TMLR: swap preamble and title block ------------------------------
    body = body_after_preamble(src)
    # the \maketitle title block lives in the preamble for the article class;
    # for tmlr it goes above \begin{document}
    body = re.sub(r"\\date\{[^}]*\}\n", "", body)
    tmlr = (TMLR_PREAMBLE
            + (TMLR_TITLE_NAMED if deanon else TMLR_TITLE_ANON)
            + "\n" + body)
    if not deanon:
        for pat, rep in ANON_SUBS:
            tmlr = re.sub(pat, rep, tmlr)
    os.makedirs(os.path.join(HERE, "tmlr"), exist_ok=True)
    with open(os.path.join(HERE, "tmlr", "main.tex"), "w") as f:
        f.write(tmlr)

    # literal identifying tokens, checked independently of the substitutions
    leaks = [s for s in ("oratis", "HakkoLab", "Wang Bihao", "meetlisa")
             if not deanon and s in tmlr]
    print(f"wrote arxiv/main.tex and tmlr/main.tex "
          f"({'named' if deanon else 'anonymized'})")
    if leaks:
        print(f"WARNING: identifying strings still present: {leaks}")
    elif not deanon:
        print("anonymization check: no known identifying strings remain")


if __name__ == "__main__":
    main()
